# Generated by Django 2.0.6 on 2018-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gadgets', 'Gadgets'), ('computer', 'computer'), ('antique', 'Antique'), ('phones', 'Phone'), ('misc', 'misc')], default='misc', max_length=6),
        ),
    ]
