# Generated by Django 2.0.6 on 2018-10-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gadg', 'Gadgets'), ('comp', 'computer'), ('anti', 'Antique'), ('phon', 'Phone'), ('misc', 'misc')], default='misc', max_length=6),
        ),
    ]
