# Generated by Django 2.0.6 on 2018-10-21 16:15

from django.db import migrations, models
import productpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_auto_20181019_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to=productpage.models.user_directory_path),
        ),
    ]
