# Generated by Django 2.0.6 on 2018-10-21 16:17

from django.db import migrations, models
import productpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0004_auto_20181021_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to=productpage.models.user_directory_path),
        ),
    ]
